### ISSUE TITLE
d.ts for node or browser?

### ISSUE THREAD

**Issue by makoven** [jdiamond/MQTT.ts#1]
Hey. Thanks for the library! I am converting my IoT pet project to it from MQTT.js. Also great work on typesafe adaptation for a node using "deno bundle" and babel. Did you find any way to export the declaration files from source that could be distributed along with packages for the node and browser?

**Comment by jdiamond** [comment]
Sorry, I haven't figured out how to do it yet. In a normal TypeScript project, I think I would just use `tsc -d` but I get errors about the imports using .ts extensions when I try that on my Deno code.

**Comment by jdiamond** [comment]
I hacked together a [script](https://github.com/jdiamond/MQTT.ts/blob/422e3eb532090306ca80742346990b6c7d527605/build/build-node-types.sh) to strip away the .ts extensions and generate a .d.ts file. It's published in v0.0.4 on npm. I'm getting IntelliSense and tooltips in VS Code so I think it's working.

AFAIK, package.json only has room for one `types` property so I'm not sure what to do about differentiating between the Node.js and browser types, not that there are any differences that I can think of. I could publish a separate package for Node.vs vs browsers or I could try to unify the types so there doesn't need to be a distinction.

Unrelated to the above, you are the first person besides myself trying to use this project that I know of and I'm not even using it at work yet (still using MQTT.js everywhere). I _think_ the API for the `Client` class should be pretty stable, but I see I need to clean it up and mark a bunch of stuff as private. Apologies in advance if I end up breaking any APIs on you. 😞

**Comment by makoven** [comment]
Thanks for the quick response. The corresponding issue (https://github.com/microsoft/TypeScript/issues/27481) was opened back in 2018. And still ignored by the developers. IMHO, this is a stop factor for many projects to support Deno and Node at the same time 

PS: IPA changes are not essential for my modest needs :)
